### ISSUE TITLE
LOF algo suggestion

### ISSUE THREAD

**Issue by lsqworld** [elki-project/elki#109]
[LOF.java](https://github.com/elki-project/elki/blob/master/elki-outlier/src/main/java/elki/outlier/lof/LOF.java), comparing to [scikit-learn _lof.py](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/neighbors/_lof.py#L511C65-L511C65), shall we also make a small addon to the 'sum' variable instead of returning Double.POSITIVE_INFINITY, to be compatible on scene which number of duplicated points is greater than K ?

![image](https://github.com/elki-project/elki/assets/8489467/21c37e86-de50-4b02-a228-838860127ef5)
![image](https://github.com/elki-project/elki/assets/8489467/0d216c72-2eb4-4ca3-9070-93961694b586)

**Comment by kno10** [comment]
Positive infinity is the appropriate value, which is easily seen if you make this epsilon arbitrarily small.
Hence no need for the epsilon.
In my opinion, this is better than hiding the problem with a finite value such as 1e10!

P.S. please choose meaningful issue titles, "algo suggestion" is poor.

**Comment by kno10** [comment]
Closing, as the current behaviour is desired.
