### ISSUE TITLE
 Links in https://elki-project.github.io/algorithms/ broken

### ISSUE THREAD

**Issue by SamiSieranoja** [elki-project/elki#110]
The links in https://elki-project.github.io/algorithms/ lead to 404 error.

For example: https://elki-project.github.io/releases/current/javadoc/elki/algorithm/clustering/hierarchical/AGNES.html

But if you remove "algorithm" from the url, it works:
https://elki-project.github.io/releases/current/javadoc/elki/clustering/hierarchical/AGNES.html

**Comment by kno10** [comment]
Thank you. In ELKI 0.8.0 we simplified the package hierarchy, removing, e.g., the extra "algorithm" level.
This has been fixed in [elki-project.github.io/490cc67f](https://github.com/elki-project/elki-project.github.io/commit/490cc67f7d17eb06a380e3ffb2cd7b3c93a0839d)
