### ISSUE TITLE
Proper uninstall

### ISSUE THREAD

**Issue by Syntax-Sorcerer87** [elki-project/elki#112]
Hello, I would like like to uninstall elki. i can not seem to find it in my apps uninstall options in windows. does any one know how i can do a proper uninstalll of elki ? 
thanks, and best regards

**Comment by kno10** [comment]
It does not install anything, hence it has no installer or uninstaller.

**Comment by Syntax-Sorcerer87** [comment]
There is no mention of that, any where. All i need to to know is that i can delete the files. Hence, me asking the question.
ps. When you answer simple questions with "hense" it makes you seem like a total fucking snob.
