### ISSUE TITLE
Incorrect comparision in KmedoidsPAM.java.

### ISSUE THREAD

**Issue by Machiry** [elki-project/elki#2]
Location: https://github.com/elki-project/elki/blob/master/elki/src/main/java/de/lmu/ifi/dbs/elki/algorithm/clustering/kmeans/KMedoidsPAM.java#L221
Here, the comparison needs to be with distnew. i.e distnew > distsec.
We check with new distance to see, if it is greater than the second best. The current comparison does not makes sense because distcur is always less than distsec. Thus distcur > distsec will always be false.
Am I missing something here?

**Comment by kno10** [comment]
Thank you. I believe you are right, and I will review the implementation.
Doesn't change anything in my tests though.

**Comment by kno10** [comment]
Closed with commit e84403dc5e46b85c504972f9b21544425d4aa9ce
