### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by AshutoshMishra44** [elki-project/elki#33]
ant -f C:\\Users\\336943\\Documents\\NetBeansProjects\\Clustering -Dnb.internal.action.name=build jar
init:
Deleting: C:\Users\336943\Documents\NetBeansProjects\Clustering\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\336943\Documents\NetBeansProjects\Clustering\build\built-jar.properties
Compiling 1 source file to C:\Users\336943\Documents\NetBeansProjects\Clustering\build\classes
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:111: error: method chooseInitialMeans in interface KMeansInitialization<V#2> cannot be applied to given types;
      means = initializer.chooseInitialMeans(database, relation, k, getDistanceFunction());
  required: Database,Relation<T>,int,NumberVectorDistanceFunction<? super T>,Factory<O>
  found: Database,Relation<V#1>,int,NumberVectorDistanceFunction<CAP#2>
  reason: cannot infer type-variable(s) T,O
    (actual and formal argument lists differ in length)
  where T,O,V#1,V#2 are type-variables:
    T extends CAP#1 declared in method <T,O>chooseInitialMeans(Database,Relation<T>,int,NumberVectorDistanceFunction<? super T>,Factory<O>)
    O extends NumberVector declared in method <T,O>chooseInitialMeans(Database,Relation<T>,int,NumberVectorDistanceFunction<? super T>,Factory<O>)
    V#1 extends NumberVector declared in class SameSizeKMeansAlgorithm
    V#2 extends NumberVector declared in interface KMeansInitialization
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends NumberVector super: V#1 from capture of ? super V#1
    CAP#2 extends Object super: V#1 from capture of ? super V#1
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:123: error: incompatible types: double[][] cannot be converted to List<? extends NumberVector>
    means = means(clusters, means, relation);
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:130: error: incompatible types: double[] cannot be converted to Vector
      result.addToplevelCluster(new Cluster<>(clusters.get(i), new MeanModel(means[i])));
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:151: error: cannot find symbol
        final double d = c.dists[i] = df.distance(fv, DoubleVector.wrap(means[i]));
  symbol:   method wrap(double[])
  location: class DoubleVector
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:237: error: cannot find symbol
        c.dists[i] = df.distance(fv, DoubleVector.wrap(means[i]));
  symbol:   method wrap(double[])
  location: class DoubleVector
C:\Users\336943\Documents\NetBeansProjects\Clustering\src\tutorial\clustering\SameSizeKMeansAlgorithm.java:340: error: incompatible types: double[][] cannot be converted to List<? extends NumberVector>
      means = means(clusters, means, relation);
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
6 errors
C:\Users\336943\Documents\NetBeansProjects\Clustering\nbproject\build-impl.xml:930: The following error occurred while executing this line:
C:\Users\336943\Documents\NetBeansProjects\Clustering\nbproject\build-impl.xml:270: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)

**Comment by AshutoshMishra44** [comment]
Please help me out in this regard

**Comment by kno10** [comment]
There appears to be some error in your code, but we cannot help you there: this is local on your computer.
Maybe you are mixing code of two different versions.
Please try a clean github checkout with eclipse. People have had problems with netbeans.
