### ISSUE TITLE
Clusters of size 0 (with HDBSCAN/DeLiClu/OPTICS)

### ISSUE THREAD

**Issue by neilireson** [elki-project/elki#48]
Perhaps this is related to https://github.com/elki-project/elki/issues/41 and therefore expected. 

However my (naive) understanding is that for some of these algorithms (HDBSCAN) the cluster is defined by the enclosed data points.  Therefore a zero sized cluster is meaningless.

**Comment by kno10** [comment]
In a *hierarchical* result, a 0 element cluster can make perfect sense:
it can have two non-empty child clusters (and you should always consider all child cluster members to be part of a cluster, too).
Please check the hierarchy, too.

**Comment by kno10** [comment]
Did this answer your question? Can I close the issue?
