### ISSUE TITLE
How to get the p-value of the Anderson-Darling test?

### ISSUE THREAD

**Issue by betrw** [elki-project/elki#52]
How can I get the p-value of the two samples Anderson-Darling-Test?

I used

			StandardizedTwoSampleAndersonDarlingTest ad = new StandardizedTwoSampleAndersonDarlingTest();
			pi.AndersonDarlingValue = ad.unstandardized(d1, d2);		
			pi.AndersonDarlingPValue = ad.deviation(d1, d2); //p-value ???

**Comment by kno10** [comment]
The critical values (and p-values) depend on the distribution assumptions you make on the data.
There is currently no implementation for this included - please contribute.

**Comment by kno10** [comment]
ELKI now includes code to compute p-Values for the anderson-darling test since a9b9987598f170dbeac1f943229bebd6216bbf11
