### ISSUE TITLE
CLIQUE - Connected dense units

### ISSUE THREAD

**Issue by georgekatona** [elki-project/elki#53]
Inspecting results of elki's CLIQUE clustering implementations revealed an issue of the implementation. The original paper [AGGR98](https://www.cs.cornell.edu/johannes/papers/1998/sigmod1998-clique.pdf) at paragraph 2.1 states that two dense units are connected if they have a common face (they are identical in n-1 dimensions and in 1 dimension they are neighboring).

According to this the following output should be impossible:

```
# Cluster: cluster_1
# Cluster name: cluster_1
# Cluster noise flag: false
# Cluster size: 500
# Model class: de.lmu.ifi.dbs.elki.data.model.SubspaceModel
# Cluster Mean: 0.5058922207711539, 0.5997058865585326
# Subspace: Dimensions: [1]
# Coverage: 500
# Units: 
#    d1-[0.04; 0.33[    127 objects
#    d1-[0.33; 0.62[    207 objects
#    d1-[0.62; 0.92[    166 objects
```

In this case all dense units are neighboring in both of the dimensions, yet the current implementation considers it one cluster.

**Comment by georgekatona** [comment]
Unfortunately I don't have the time to debug it completely but as I briefly looked into it, I would start debugging around [here](https://github.com/elki-project/elki/blob/b669f94d8f916ef331a6d8684682a0de1f0568ff/elki-clustering/src/main/java/de/lmu/ifi/dbs/elki/algorithm/clustering/subspace/clique/CLIQUESubspace.java#L132).

**Comment by kno10** [comment]
Actually I do not see what is wrong with above output.
It is one cluster; it consists of three units. The cluster is n=1 dimensional. The three units are identical in n-1=0 dimensions, and they are neighbors in 1. So this seems to agree with the definitions.

**Comment by georgekatona** [comment]
Oh, you are right, I copied the wrong cluster. I experienced the error in the two dimensional feature space:

```
# Cluster: cluster_3
# Cluster name: cluster_3
# Cluster noise flag: false
# Cluster size: 333
# Model class: de.lmu.ifi.dbs.elki.data.model.SubspaceModel
# Cluster Mean: 0.4916644248110665, 0.6574075443435105
# Subspace: Dimensions: [1, 2]
# Coverage: 333
# Units: 
#    d1-[0.04; 0.33[ d2-[0.64; 0.90[    101 objects
#    d1-[0.33; 0.62[ d2-[0.39; 0.64[    127 objects
#    d1-[0.62; 0.92[ d2-[0.64; 0.90[    105 objects
```

**Comment by kno10** [comment]
I may have a fixed version ready to go, but I don't have a test case to verify this.

**Comment by georgekatona** [comment]
I have ran it on the [mouse](https://github.com/elki-project/elki/blob/master/data/synthetic/Vorlesung/mouse.csv) sample data set with xsi = 3, tau = 0.1.

**Comment by kno10** [comment]
Thanks. It seems that the rewrite committed above resolves this. It should also be faster, but this is untested - the code is still not optimized much (but it probably also is not worth the time doing so).
