### ISSUE TITLE
Could not find logging configuration file "logging.properties" in version 0.7.1

### ISSUE THREAD

**Issue by aguslarla** [elki-project/elki#58]
Hi!
I apologise for disturbing if i am wrong for openning this issue here.

I am using Elki v.0.7.1 library in my project and i am obtain the message in subject issue. 
I have checked the library and the "logging.properties" file exists. 

I attach two screenshots with the issue.

I hope your answer. Thanks a lot.
![error_elki](https://user-images.githubusercontent.com/13064163/54029378-797c2100-41a8-11e9-8e7e-7d70802650be.png)
![elki_library](https://user-images.githubusercontent.com/13064163/54029386-7e40d500-41a8-11e9-89f7-4c46b1a9cd9d.png)

**Comment by kno10** [comment]
As you noticed, the file is where it is supposed to be, so I don't think ELKI is to blame here.

But you most likely have a modified class loader setup, and that is where the problem supposedly is.

**Comment by aguslarla** [comment]
Hi Erich! 

Thanks for your fast answer. I am going to review my code carefully but at simple view, i don´t see nothing wrong.

**Comment by kno10** [comment]
It likely is not obvious in the code; but rather a question of how it is launched (in particular, of the classpath and class loader). For example, building fat jars could break this.
The screenshot you shared indicate that there is at least some other logging framework loaded that could also cause interference.

The packaged logging.properties is loaded via `ClassLoader.getSystemResourceAsStream`, and that can break with custom class loading.

https://github.com/elki-project/elki/blob/6f1d3995960e5ce3e468b1e9e8cf202263c12ba7/elki/src/main/java/de/lmu/ifi/dbs/elki/logging/LoggingConfiguration.java#L158

In the latest version 0.7.5, this will use the classes own classloader, which is much more reliable:

https://github.com/elki-project/elki/blob/474659eba15a27525db5f4c76162f28a7f1733aa/elki-logging/src/main/java/de/lmu/ifi/dbs/elki/logging/LoggingConfiguration.java#L158-L159

As a workaround you can simply try to provide a customized logging.properties file.
