### ISSUE TITLE
Naming JUnit tests

### ISSUE THREAD

**Issue by deric** [elki-project/elki#6]
It's quite good convention to name JUnit test files with suffix `Test`, [not a prefix](http://stackoverflow.com/questions/3146821/naming-convention-junit-suffix-or-prefix-test).

It makes much easier to read the code, as most IDEs support switching between class and its test.

Would you accept a PR with renaming test files?

**Comment by kno10** [comment]
This is of very low priority to me, but I will do this eventually.
Both have their benefits and drawbacks. Having the Test sorted next to the class is nice; but not having the Tests mixed up with the classes (but below) is also nice.

I would appreciate contributions that add more test coverage much more than renaming the classes. Code coverage is rather low, unfortunately (although a lot higher than I expected).

**Comment by kno10** [comment]
I have written a tiny script and done that renaming and pushed a56afc9. Some other class names are odd now: e.g. AndersonDarlingTestTest to test the class implementing the anderson darling test. ;-)
I also got rid of the "Results" postfix some student probably used back then, e.g. TestDBSCANResult -> DBSCANTest. Maybe that was also meant to reflect the fact that the unit test is a regression test that only looks at the overall clustering result; we unfortunately do not have tests that test individual methods.

**Comment by deric** [comment]
Cool, thanks!
