### ISSUE TITLE
Naive quantiles for exponentially modified gaussian

### ISSUE THREAD

**Issue by jcfj** [elki-project/elki#62]
I needed 99% and 99.9% quantiles for an EMG and was able to get decent results with something as simple as
```java
double x = emg.getMean() + emg.getStddev() - Math.log(1 - qt) / emg.getLambda();
for (int i = 0; i < 10; i++)
    x -= (emg.cdf(x) - qt) / emg.pdf(x);
```

I'm wondering: is that worthy of a PR, or too stupid?

**Comment by kno10** [comment]
I'd prefer something that has been checked for numerical reliability.
