### ISSUE TITLE
Fails to build with gradle-5.6

### ISSUE THREAD

**Issue by yurivict** [elki-project/elki#64]
Log: https://people.freebsd.org/~pi/logs/elki-0.7.1.1166.log

Downstream report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239900

**Comment by kno10** [comment]
It fails to build offline if you don't have the dependencies, yes.
But that is your responsibility to make them available offline.
Also, please use 0.7.5, released in Feburary.
