### ISSUE TITLE
[doc] missing variable c

### ISSUE THREAD

**Issue by deric** [elki-project/elki#7]
In [documentation](http://elki.dbs.ifi.lmu.de/wiki/HowTo/InvokingELKIFromJava):

```java
// Relation containing the number vectors:
Relation<NumberVector> rel = db.getRelation(TypeUtil.NUMBER_VECTOR_FIELD);
// We know that the ids must be a continuous range:
DBIDRange ids = (DBIDRange) rel.getDBIDs();

int i = 0;
for(Cluster<KMeansModel> clu : c.getAllClusters()) {
```
The variable `c.getAllClusters()` is undefined.

**Comment by kno10** [comment]
These are only fragments. It should be fairly obvious that `c` is the clustering result from running KMeans. The fragment above is missing a line, `c = km.run(db);` - the full example can be found in the tutorial addon.
