### ISSUE TITLE
ParallelGeneralizedDBSCAN missing from latest release?

### ISSUE THREAD

**Issue by mmisiewicz-yext** [elki-project/elki#74]
As the title suggests I was wondering if it's expected that the parallelized DBSCAN implementation is not present in the the release 0.7.1 jar file. The Javadocs on elki-project.github.io still mention it. 

For reference: 
```
$  jar tf elki-0.7.1.jar | grep -i dbscan | grep -i parallel | wc -l
       0
```

**Comment by kno10** [comment]
The latest release is 0.7.5, not 0.7.1.

It was added in 0.7.5.

**Comment by mmisiewicz-yext** [comment]
Whoops, thank you!
