### ISSUE TITLE
Any docs about DeLiClu clustering algorithm?

### ISSUE THREAD

**Issue by GF-Huang** [elki-project/elki#77]
I had read this [paper](https://www.dbs.ifi.lmu.de/Publikationen/Papers/paper-DeliClu-annotated.pdf), but it's hard to understand its algorithm logic for me, is there any docs about this algorithm?

**Comment by kno10** [comment]
Closing as this rather is a question about that paper than about ELKI.

To understand the paper, it will likely help if you study the references therein. In particular:
8.  Böhm, C., Krebs, F.:  The k-nearest neighbor join: Turbo charging the KDD process.  KAIS 6(2004)
10.  Böhm, C., Kriegel, H.P.: A cost model and index architecture for the similarity join. In: Proc.ICDE. (2001)
but also the other references on OPTICS, CPR, and k nearest neighbor joins.

**Comment by GF-Huang** [comment]
OK, thanks your guide.
