### ISSUE TITLE
hello [Parser-ing]

### ISSUE THREAD

**Issue by directorscut82** [elki-project/elki#8]
& thanks for ELKI

Dont have any mighty algos but if yr interested in a parser for numerical matlab (.mat) files i made one wrapping this [jmatio](https://github.com/diffplug/matfilerw)

It is based on yours arff parser (i copied everything;) but it works

**Comment by kno10** [comment]
Since we want to keep external dependencies low, this would be a good candidate for an optional add-on.

**Comment by directorscut82** [comment]
i send email to your dbs.ifi.lmu.de address
