### ISSUE TITLE
Fastutil >8.5.3 not supported  

### ISSUE THREAD

**Issue by flexkra** [elki-project/elki#83]
FastUtil removed Int2Float-components in 8.5.3 and 8.5.4 therefore these versions cannot be used. Latest working version is 8.5.2.

**Comment by kno10** [comment]
Shouldn't this be fixed by fastutil 8.5.4? Apparently 8.5.3 was bad though.
```
jar tf fastutil-8.5.4.jar| grep Int2FloatOpenHashMap
```
does list the classes. For 8.5.3 does not. Then it would be a (resolved) bug in fastutil.

**Comment by flexkra** [comment]
Yes, it is fixed by 8.5.4. I accidentally checked 8.5.3 twice. However, gradle still pulls 8.5.3 as latest version.
