### ISSUE TITLE
Eclipse Mars launch of MiniGUI fails

### ISSUE THREAD

**Issue by frewenta** [elki-project/elki#86]
I followed the eclipse configuration for Elki and console indicates build was successful
But when I try to run ELKI MiniGUI from Run Configurations it fails with:

An internal error occurred during: "Launching ELKI MiniGUI".
Model not available for elki

**Comment by kno10** [comment]
Why are you still using Eclipse Mars from **2015**?
Use a recent Eclipse, which has improved Gradle build support. That is probably causing your problem.

**Comment by frewenta** [comment]
I get the same behavior (following instructions at  https://elki-project.github.io/dev/eclipse) 
using a 2021 version of eclipse 
(downloaded from https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2021-03/R/eclipse-inst-jre-win64.exe&mirror_id=1135)

**Comment by kno10** [comment]
Which Java *JDK* do you have installed?
There are known Gradle issues with Java 17, for example.

The error message *is* known from Eclipse-Gradle problems: https://www.google.com/search?q=%22Model+not+available+for%22

**Comment by kno10** [comment]
Apparently you have resolved the issue somehow.
Can you let us know how, in case someone else has the same error?
Thank you.
