### ISSUE TITLE
Build Issue: :elki-logging:compileJava - NullPointerException

### ISSUE THREAD

**Issue by lapplislazuli** [elki-project/elki#91]
Hi, 

I'm trying to build as per README within a Docker, and my Gradle Build is failing. 

I use the following short Dockerfile: 

```Dockerfile
FROM gradle:7.1-jre11
#FROM gradle:7.1-jre8

WORKDIR /build

COPY . .

RUN ["./gradlew","build","--stacktrace"]
```

which gives the following 

```
[...]
#8 33.82 > Task :elki-core-util:generateCodeArrays
#8 34.62 > Task :elki-core-util:generateCodeHeaps
#8 34.82 > Task :elki-logging:compileJava FAILED
#8 34.82 
#8 34.82 FAILURE: Build failed with an exception.
#8 34.82 
#8 34.82 * What went wrong:
#8 34.82 Execution failed for task ':elki-logging:compileJava'.
#8 34.82 > java.lang.NullPointerException (no error message)
#8 34.82 
#8 34.82 * Try:
#8 34.82 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#8 34.82 
#8 34.82 * Exception is:
#8 34.82 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':elki-logging:compileJava'.
[...]
```
(Full file [output.log](https://github.com/elki-project/elki/files/6716841/output.log))

I have this also outside of the Docker. I get the same errors for gradle jar and gradle shadowjar, also on JDK8.

**Comment by kno10** [comment]
Clearly this is an error in *Gradle*, not in ELKI.

My guess is that you did not install a Java JDK, and hence your docker container cannot compile Java.

Try using a JDK container, not a JRE container.

If that resolves the issue, please file a bug with gradle to provide a more helpful error message (e.g., "no JDK installed") instead of a NPE.

**Comment by lapplislazuli** [comment]
@kno10 Thanks, that ... I feel ashamed now :S

**Comment by kno10** [comment]
It's not your fault. Gradle should provide a better error message instead of

> java.lang.NullPointerException (no error message)

**Comment by kno10** [comment]
FYI: the next version of Gradle should report "Java compiler is not available." via gradle/gradle/pull/17617
