### ISSUE TITLE
SUBCLU: Why call DBSCAN d-times with the same DB?

### ISSUE THREAD

**Issue by samuelm00** [elki-project/elki#98]
Referring to this file https://github.com/elki-project/elki/blob/master/elki-clustering/src/main/java/elki/clustering/subspace/SUBCLU.java

form line `166` to `184` the algorithm generates all 1-dimensional clusters, but why do you run DBSCAN with the same parameters d times (the result should always be the same)?

**Comment by kno10** [comment]
Its running DBSCAN on d different subspaces, isn't it?
